Transform: AWS::Serverless-2016-10-31

Parameters: 
  WebhookURL:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/WEBHOOK_URL
  Environment:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/ENVIRONMENT

Resources:
  LidtCheckerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lidt-checker
      Runtime: go1.x
      MemorySize: 1024
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
          APP_ENV: !Ref Environment
      Events:
        mEveryMinuteSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)