Transform: AWS::Serverless-2016-10-31

Parameters: 
  AuthorIcon:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/AUTHOR_ICON
  AuthorName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/AUTHOR_NAME
  AuthorURL:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/AUTHOR_URL
  AvatarURL:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/AVATAR_URL
  MessageColour:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/MESSAGE_COLOUR
  MessageLink:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/MESSAGE_LINK
  WebhookURL:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/WEBHOOK_URL
  WebhookUsername:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /lidt-checker/WEBHOOK_USERNAME

Resources:
  JapanTourismLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lidt-checker
      Runtime: go1.x
      MemorySize: 1024
      Environment:
        Variables:
          AUTHOR_ICON: !Ref AuthorIcon
          AUTHOR_NAME: !Ref AuthorName
          AUTHOR_URL: !Ref AuthorURL 
          AVATAR_URL: !Ref AvatarURL 
          MESSAGE_COLOUR: !Ref MessageColour 
          MESSAGE_LINK: !Ref MessageLink 
          WEBHOOK_URL: !Ref WebhookURL 
          WEBHOOK_USERNAME: !Ref WebhookUsername 
      Events:
        mMonthlyJapanSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * 2#1 *)